### ISSUE TITLE
"No module named 'dotenv'" and "Can not used ImageField because Pillow is not installed" errors

### ISSUE THREAD

**Issue by Al3xDo** [Ronik22/Django_PizzaHub#1]
Hi Ronik22,
I have cloned your code but It seems like you forgot to add these libraries (python-dotenv and Pillow) to  your requirements.
![image](https://user-images.githubusercontent.com/56794124/161428820-2fd6496a-b9ed-401b-8941-ab2cb270fbfc.png)
![image](https://user-images.githubusercontent.com/56794124/161428895-76358193-f5ca-4472-86f2-1febff5e8450.png)

**Comment by Ronik22** [comment]
Fixed it, Thanks Al3xDo!
