### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The ALLOWED_HOSTS setting must be a list or a tuple.

### ISSUE THREAD

**Issue by Al3xDo** [Ronik22/Django_PizzaHub#2]
Hi Ronik22,
I have the error when I run the web.
![image](https://user-images.githubusercontent.com/56794124/161429298-373cc04d-9bd3-459b-8633-6105a9309e0a.png)
I have fixed it thanks to the link https://stackoverflow.com/questions/53599307/how-to-pass-a-list-tuple-into-an-environment-variable-for-django
You can consider fixing it like this.
![image](https://user-images.githubusercontent.com/56794124/161429889-e61fda81-b951-4f6f-bc41-f04e337e912b.png)
![image](https://user-images.githubusercontent.com/56794124/161429860-f7aa8bee-84df-42c2-a4f9-a94569cf584d.png)

**Comment by Ronik22** [comment]
Fixed it. Thanks, Al3xDo!
